// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectWorkServiceCatalogo.DL;

#nullable disable

namespace ProjectWorkServiceCatalogo.DL.Migrations
{
    [DbContext(typeof(CatalogoServiceDbContext))]
    [Migration("20231109133907_add-prodotto")]
    partial class addprodotto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectWorkServiceCatalogo.DL.Models.TbCategoria", b =>
                {
                    b.Property<long>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCategoria"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NOME");

                    b.HasKey("IdCategoria");

                    b.ToTable("CATEGORIA");
                });

            modelBuilder.Entity("ProjectWorkServiceCatalogo.DL.Models.TbProdotto", b =>
                {
                    b.Property<long>("IdProdotto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdProdotto"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("text")
                        .HasColumnName("DESCRIZIONE");

                    b.Property<int>("Disponibilita")
                        .HasColumnType("integer")
                        .HasColumnName("DISPONIBILITA");

                    b.Property<long>("FkCategoria")
                        .HasMaxLength(50)
                        .HasColumnType("bigint")
                        .HasColumnName("FK_CATEGORIA");

                    b.Property<string>("Immagine")
                        .HasColumnType("text")
                        .HasColumnName("IMMAGINE");

                    b.Property<string>("Materiale")
                        .HasColumnType("text")
                        .HasColumnName("MATERIALE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NOME");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("numeric")
                        .HasColumnName("PESO");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("numeric")
                        .HasColumnName("PREZZO");

                    b.HasKey("IdProdotto");

                    b.HasIndex("FkCategoria");

                    b.ToTable("PRODOTTO");
                });

            modelBuilder.Entity("ProjectWorkServiceCatalogo.DL.Models.TbProdotto", b =>
                {
                    b.HasOne("ProjectWorkServiceCatalogo.DL.Models.TbCategoria", "FkCategoriaNavigation")
                        .WithMany()
                        .HasForeignKey("FkCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkCategoriaNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
